# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Bankey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit', '~> 5.7.0'

  # Pods for Bankey

  target 'BankeyUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
